name: Check Markdown links

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
