name: Check Markdown links 2

on: 
  push:
    branches:
      - develop

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
