name: Check Markdown links

on: [push, pull_request]
  branches:
    - develop

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
