name: Check Markdown links

on: [push]

jobs:
  markdown-link-check1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'https://raw.githubusercontent.com/Yuri05/docs/master/.github/workflows/mlc_config.json'
  markdown-link-check2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: serokell/xrefcheck-action@v1
