name: Test1
on: [push]
jobs:
  test1:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
      - name: setup remark cli
        run: npm install -g remark-cli remark-validate-links --quiet --no-progress
      - name: validate links
        run: remark -u validate-links . -f
      - name: Upload Readme
        uses: actions/upload-artifact@v1
        with:
          name: readme
          path: README.md
  
  
  
